name: Update Page

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-page:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        
    - name: Get update
      env:
        TEMPEST_PUT: ${{ secrets.TEMPEST_PUT }}
      run: python .github/update-page.py
      
    - name: Configure Git
      run: git config --global user.name "RabbitAtHope" && git config --global user.email "rabitoy@hope.edu"
      
    - name: Commit changes
      run: git add index.html && git commit -m "Update page" && git push || echo "No changes"
